coding:
  http:
    port: ${CODING_HTTP_PORT:8080}

grpc:
  port: ${RPC_SERVER_PORT:20153}
  enableReflection: true
  client:
    coding:
      serviceName: ${CODING_SERVICE_NAME:coidng}
      servicePort: ${CODING_SERVICE_PORT:20153}

jdbc:
  host: ${JDBC_HOST:jdbc:mysql://9.135.93.238:3306/coding}
  username: ${JDBC_USERNAME:coding}
  password: ${JDBC_PASSWORD:coding123}

logging:
  level:
    org.lognet.springboot.grpc: info
  config: classpath:logback.xml

spring:
  redis:
    host: ${REDIS_HOST:9.135.93.238}
    port: ${REDIS_PORT:6379}
    timeout: 3600
    database: 0
    pool:
      max-wait: 3600
      max-idle: 1
      min-idle: 1


gprc:
  client:
    coding:
      serviceName: ${CODING_CLIENT_HOST:-coding}
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      addresses: http://9.135.93.238:8080/admin
    executor:
      appname: platform-project
      port: 9981
      ip:
      logpath: ${LOG_PATH:-/Users/guangboliu/data/xxl-job/jobhandler}
      logretentiondays: 7
    accessToken: a3434ff20d1cdf6c4aa9547c841b311d
