coding:
  http:
    port: 9003


etcd:
  machines: http://etcd:2380
  discovery_path: /git-servers


grpc:
  port: 30150
  enableReflection: true

jdbc:
  host: mariadb
  database: coding
  username: coding
  password: coding123

amqp:
  url: amqp://guest:guest@rabbitmq:5672/


eventbus:
  appName: project


logging:
  level:
    org.lognet.springboot.grpc: INFO