coding:
  http:
    port: ${CODING_HTTP_PORT:8080}

sentry:
  enable: true
  appname: ${SENTRY_APPNAME:platform-project}
  dsn: ${SENTRY_DSN:-http://2579a9f6b53e4bc5b46199c2066c8493:6ef2ec6a73374e2fa8aa5eb6939784f3@127.0.0.1:9000/3}

grpc:
  port: ${RPC_SERVER_PORT:20153}
  enableReflection: true
  client:
    coding:
      serviceName: ${CODING_SERVICE_NAME:9.135.93.238}
      servicePort: ${CODING_SERVICE_PORT:20153}

jdbc:
  host: ${JDBC_HOST:jdbc:mysql://9.135.93.238:3306/coding}
  username: ${JDBC_USERNAME:coding}
  password: ${JDBC_PASSWORD:coding123}

logging:
  level:
    org.lognet.springboot.grpc: info
  config: classpath:logback.xml

spring:
  redis:
    host: ${REDIS_HOST:9.135.93.238}
    port: ${REDIS_PORT:6379}
    timeout: 3600
    database: 0
    pool:
      max-wait: 3600
      max-idle: 1
      min-idle: 1

gprc:
  client:
    coding:
      serviceName: ${CODING_CLIENT_HOST:-coding}

log4j:
  rootLogger=console

#xxl:
#  job:
#    admin:
#      addresses: ${PLATFORM_XXL_JOB:http://9.135.93.238:8080}/admin
#    executor:
#      appname: platform-project
#      port: 9981
#      ip:
#    accessToken: a3434ff20d1cdf6c4aa9547c841b311d