coding:
  http:
    port: 9003


etcd:
  machines: http://9.135.93.238:2379
  discovery_path: /git-servers


grpc:
  port: 30151
  enableReflection: true

jdbc:
  host: jdbc:mysql://9.135.93.238:3306/coding?serverTimezone=Asia/Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: coding
  password: coding123


logging:
  level:
    org.lognet.springboot.grpc: info

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl