coding:
  http:
    port: ${CODING_HTTP_PORT:9003}


etcd:
  machines: ${ETCD_MACHINES:http://9.135.93.238:2379}
  discovery_path: /git-servers


grpc:
  port: ${RPC_SERVER_PORT:20153}
  enableReflection: true

jdbc:
  host: ${JDBC_HOST:jdbc:mysql://9.135.93.238:3306/coding}
  username: ${JDBC_USERNAME:coding}
  password: ${JDBC_PASSWORD:coding123}

logging:
  level:
    org.lognet.springboot.grpc: info

spring:
  redis:
    host: ${REDIS_HOST:9.135.93.238}
    port: ${REDIS_PORT:6379}
    timeout: 3600
    database: 0
    pool:
      max-wait: 3600
      max-idle: 1
      min-idle: 1

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl