---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-project-config
data:
  JAVA_OPTS: "-Xms512m -Xmx512m ${JAVA_EXTRA_OPTS}"
  CODING_HTTP_PORT: "8080"
  RPC_SERVER_PORT: "20153"
  JDBC_HOST: jdbc:mysql://mariadb/coding
  JDBC_DATABASE: coding
  JDBC_USERNAME: coding
  JDBC_PASSWORD: coding123
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  AMQP_URL: amqp://guest:guest@rabbitmq:5672/
  CODING_SERVICE_NAME: coding
  CODING_SERVICE_PORT: "20153"
...