---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-project
  annotations:
    apiAuth: |-
      [ {
        "mappings" : {
          "path" : "/api/platform/project/{projectId}/notice",
          "method" : [ "POST" ]
        },
        "enterpriseAction" : "Create",
        "enterpriseFunction" : "ProjectNotice"
      }, {
        "mappings" : {
          "path" : "/api/platform/project/{projectId}/notice/{id}",
          "method" : [ "PUT" ]
        },
        "enterpriseAction" : "Update",
        "enterpriseFunction" : "ProjectNotice"
      }, {
        "mappings" : {
          "path" : "/api/platform/project/{projectId}/notice/{id}",
          "method" : [ "DELETE" ]
        },
        "enterpriseAction" : "Update",
        "enterpriseFunction" : "ProjectNotice"
      } ]
    apiRoute: |-
      [ {
        "path" : "/api/platform/project/resources/**"
      }, {
        "path" : "/ping",
        "method" : "GET"
      }, {
        "path" : "/",
        "method" : "GET"
      }, {
        "path" : "/api/platform/project/{projectId}/notice/**"
      } ]
spec:
  selector:
    matchLabels:
      app: platform-project
  replicas: 1
  template:
    metadata:
      labels:
        app: platform-project
    spec:
      enableServiceLinks: false
      initContainers:
        - name: pod-dependency
          image: ylonkar/pod-dependency-init-container:1.0.2
          env:
            - name: POD_LABELS
              value: app=mariadb,app=redis
      containers:
        - name: platform-projeect
          image: ${CODING_API_DOCS_BACKEND_IMAGE:-codingcorp-docker.pkg.coding.net/registry/build/platform-project:5f92cf8010e1ab71ba836a20f8ff0bd9dd0635e4}
          ports:
            - containerPort: 8080
            - containerPort: 20153
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          envFrom:
            - configMapRef:
                name: platform-project-config
      imagePullSecrets:
        - name: codingcorp-registry-cred
...